CREATE TABLE link_chat
(
    id         BIGHT     GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    chat_id    BIGHT     NOT NULL REFERENCES chat (id) ON DELETE CASCADE UNIQUE,
    link_id    BIGHT     NOT NULL REFERENCES link (id) ON DELETE CASCADE UNIQUE,
    created_at TIMESTAMP NOT NULL
)
