CREATE TABLE link_chat
(
    id         BIGINT     GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    chat_id    BIGINT     NOT NULL REFERENCES chat (id) ON DELETE CASCADE UNIQUE,
    link_id    BIGINT     NOT NULL REFERENCES link (id) ON DELETE CASCADE UNIQUE,
    created_at TIMESTAMP NOT NULL
)
