app:
  stack-overflow-url:
    default-url: https://api.stackexchange.com/2.3/
  git-hub-url:
    default-url: https://api.github.com/
  telegram-bot-url:
    default-url: http://localhost:8090/bot/api/v1/
  scheduler:
    enable: true
    interval: 2s
    force-check-delay: 10s

spring:
  application:
    name: scrapper
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    password: postgres
    username: postgres
  docker:
    compose:
      enabled: true
      file: compose.yml

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml
