/*
 * This file is generated by jOOQ.
 */
package edu.java.domain.jooq.public_;


import edu.java.domain.jooq.DefaultCatalog;
import edu.java.domain.jooq.public_.tables.Chat;
import edu.java.domain.jooq.public_.tables.GitHubRepositories;
import edu.java.domain.jooq.public_.tables.Link;
import edu.java.domain.jooq.public_.tables.LinkChat;
import edu.java.domain.jooq.public_.tables.StackOverflowQuestions;

import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.chat</code>.
     */
    public final Chat CHAT = Chat.CHAT;

    /**
     * The table <code>public.git_hub_repositories</code>.
     */
    public final GitHubRepositories GIT_HUB_REPOSITORIES = GitHubRepositories.GIT_HUB_REPOSITORIES;

    /**
     * The table <code>public.link</code>.
     */
    public final Link LINK = Link.LINK;

    /**
     * The table <code>public.link_chat</code>.
     */
    public final LinkChat LINK_CHAT = LinkChat.LINK_CHAT;

    /**
     * The table <code>public.stack_overflow_questions</code>.
     */
    public final StackOverflowQuestions STACK_OVERFLOW_QUESTIONS = StackOverflowQuestions.STACK_OVERFLOW_QUESTIONS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    @NotNull
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    @NotNull
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Chat.CHAT,
            GitHubRepositories.GIT_HUB_REPOSITORIES,
            Link.LINK,
            LinkChat.LINK_CHAT,
            StackOverflowQuestions.STACK_OVERFLOW_QUESTIONS
        );
    }
}
